config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  
  get "profile/refresh/:id", to: "profiles#refresh", as: 'refresh'
  root :to => 'profiles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness:true
    validates :git_url, presence: true
    validates :git_url, uniqueness: true
    validates :git_username, presence: true
    validates :followers, presence: true
    validates :following, presence: true
    validates :stars_given, presence: true
    validates :profile_pic_url, presence: true
    validates :last_years_contributions, presence: true

    # Method to query the Profile objects with a search param
    # @param [String] search String to be searched on name, git_username, location or organizations
    # @return [Profile] Object query if string match or all objects
    def self.search(search)
        profiles = all
        
        if search
            results = profiles.where("name LIKE ? OR git_username LIKE ? OR organizations LIKE ? OR localization LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
            unless results.nil?
                profiles = results
            end
        end

        return profiles
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_scrapper.rb
require 'nokogiri'
require 'httparty'
require 'shorturl'


module GithubScrapper

    # Method to webscrap the html of the github user profile page to retrieve data
    # @param [String] profile_url The github link to the profile
    # @return [Hash] user_profile Retrieved user data
    def web_scrap_user_profile(profile_url)

        shortened_url = shorten_url(profile_url)
        profile_web_page = HTTParty.get(profile_url)

        if profile_web_page.code != 200
            raise "Ocorreu um erro ao recuperar o perfil da url #{profile_url}"
        end
        
        parsed_profile_page = Nokogiri::HTML(profile_web_page)

        git_username = parsed_profile_page.css('span.p-nickname').text
        followers =  parsed_profile_page.css('span.text-bold.text-gray-dark')[0].text
        following = parsed_profile_page.css('span.text-bold.text-gray-dark')[1].text
        stars_given = parsed_profile_page.css('span.text-bold.text-gray-dark')[2].text
        profile_pic_url = parsed_profile_page.css('img.avatar-user')[0].attributes["src"].value
        
        last_years_contributions = parsed_profile_page.css('h2.f4.text-normal').text
        last_years_contributions = last_years_contributions.scan(/\d+/)[0]

        user_profile = {
            shortened_url: shortened_url,
            git_username: git_username,
            followers: followers,
            following: following,
            stars_given: stars_given,
            last_years_contributions: last_years_contributions,
            profile_pic_url: profile_pic_url,
        }

        # Append optional params
        profile_organizations = parsed_profile_page.css('a.avatar-group-item')
        localization = parsed_profile_page.css('ul.vcard-details span.p-label')
        
        unless localization.empty?
            localization = localization.first.text.strip()
            user_profile[:localization] = localization
        end

        unless profile_organizations.empty?
            organizations = Array.new
            for org in profile_organizations do
                organizations.push(org['aria-label'])
            end
            organizations = organizations.join(', ')

            user_profile[:organizations] = organizations
        end

        return user_profile
    end

    # Method to shorten url using external services, Default service = tinyurl
    # @param [String] url Url to be shortened
    # @return [String] shortened_url Shortened url if no external services exceptions occurr
    def shorten_url(url)
        begin
            shortened_url = ShortURL.shorten(url, :tinyurl)
        rescue
            shortened_url = url
        end

        return shortened_url
    end

end

app/controllers/profiles_controller.rb
require 'github_scrapper'

class ProfilesController < ApplicationController
  include GithubScrapper

  def index
    @profiles = Profile.search(params[:search])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(create_profile_params)

    begin
      github_data = web_scrap_user_profile(@profile.git_url)
    rescue
      flash[:errors] = Array("Não foi possível recuperar os dados da url especificada.")
      redirect_to new_profile_path
      return
    end

    unless github_data.nil?
      @profile.attributes = {
        git_url: github_data[:shortened_url],
        git_username: github_data[:git_username],
        followers: github_data[:followers],
        following: github_data[:following],
        stars_given: github_data[:stars_given],
        profile_pic_url: github_data[:profile_pic_url],
        last_years_contributions: github_data[:last_years_contributions]
      }
      
      # Optional attributes
      unless not github_data.has_key? :localization
        @profile.localization = github_data[:localization]
      end
  
      unless not github_data.has_key? :organizations
        @profile.organizations = github_data[:organizations]
      end

    end

    if @profile.save and @profile.valid?
      redirect_to profiles_path
    else
      flash[:errors] = @profile.errors.full_messages
      redirect_to new_profile_path
    end

  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(update_profile_params)

      unless not @profile.valid? and @profile.save
        flash[:errors] = @profile.errors.full_messages
      end

      if @profile.save
        @profile.git_url = shorten_url(update_profile_params[:git_url])
        @profile.save
      end

      redirect_to profile_path(@profile)
    else
      flash[:errors] = @profile.errors.full_messages
      render :edit
    end

  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to profiles_path
  end

  def refresh
    @profile = Profile.find(params[:id])

    begin
      github_data = web_scrap_user_profile(@profile.git_url)
    rescue
      flash[:errors] = Array("Não foi possível recuperar os dados da url especificada.")
      redirect_to profile_path(@profile)
      return
    end

    @profile.attributes = {
      name: @profile.name,
      git_url: @profile.git_url,
      git_username: github_data[:git_username],
      followers: github_data[:followers],
      following: github_data[:following],
      stars_given: github_data[:stars_given],
      profile_pic_url: github_data[:profile_pic_url],
      last_years_contributions: github_data[:last_years_contributions]
    }

    # Optional attributes
    unless not github_data.has_key? :localization
      @profile.localization = github_data[:localization]
    end

    unless not github_data.has_key? :organizations
      @profile.organizations = github_data[:organizations]
    end

    if @profile.valid?
      @profile.save
    else
      redirect_to profile_path(@profile), flash: { error: "Ocorreu um erro ao recuperar as informações do github."}
    end

    redirect_to profile_path(@profile)
  end


  private

  def create_profile_params
    params.require(:profile).permit(
      :name, 
      :git_url, 
      :git_username, 
      :followers, 
      :following, 
      :stars_given, 
      :profile_pic_url, 
      :last_years_contributions,
      :organizations,
      :localization
    )
  end

  def update_profile_params
    params.require(:profile).permit(
      :name,
      :git_url
    )
  end

  def profile_search_params
    params.require(:profile).permit(
      :name, 
      :git_url, 
      :git_username, 
      :followers, 
      :following, 
      :stars_given, 
      :profile_pic_url, 
      :last_years_contributions,
      :organizations,
      :localization,
      :search
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Indexador de perfis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  </head>

  <body>
    <nav class="blue-grey">
      <div class="nav-wrapper">
        <%= link_to raw("<i class=\"fab fa-github brand-logo center main-logo\"></i>"), profiles_path, method: :get %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <%= link_to  "ADICIONAR NOVO PERFIL", new_profile_path %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://kit.fontawesome.com/ce1ffb7974.js" crossorigin="anonymous"></script>
  </body>

</html>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<h4>Editar perfil</h4>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
<% end %>

<%= form_for(@profile) do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :git_url%>
    <%= f.text_field :git_url%>

    <%= f.submit 'Salvar Alterações', :class => 'btn right' %>
    <%= link_to  "Voltar", profile_path(@profile), :class => 'btn left red' %>
<% end %>

app/views/profiles/index.html.erb
<head>
    <title>Indexador de perfis</title>
</head>

<body>
    <h4>Indexador de Perfis</h4>

    <%= form_tag(profiles_path, method: :get) do %>
        <div class="row">
            <div class="input-field inline col s12">
                <%= text_field_tag(:search, params[:search], :id => :search) %>
                <label for="search">Buscar</label>
                <span class="helper-text" data-error="wrong" data-success="right">Procure por nome, username, organização ou localização</span>
            </div>
        </div>

        <div>
        </div>
        <%= submit_tag("Buscar", :class => 'btn right') %>
    <% end %>

    <div class="profile-list">
        <% Array(@profiles).each do |profile|%>
            <div class="profile-item-container">

                <div class="profile-card-content z-depth-1">
                    <%= image_tag profile.profile_pic_url, :class => 'circle profile-index-image' %>
                    <div class="profile-info">
                        <i class="far fa-edit"></i>
                        <%= link_to profile.name, profile_path(profile) %>
                    </div>
                </div>

                <div class="github-info z-depth-2">
                    <div>
                        <i class="fab fa-github"></i>
                        <%= link_to profile.git_username, profile.git_url %>
                    </div>
                </div>

            </div>
        <% end %>
    </div>

</body>

app/views/profiles/new.html.erb
<h4>Novo perfil</h4>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
<% end %>

<%= form_for(@profile) do |f| %>
    <%= f.label "nome"%>
    <%= f.text_field :name%>

    <%= f.label "Url do perfil do github"%>
    <%= f.text_field :git_url%>

    <%= f.submit 'Adicionar perfil', :class => 'btn right' %>
<% end %>

app/views/profiles/show.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <p style="color: red"><%= error %></p>
    <% end %>
<% end %>

<div class="profile-container">

    <div class="card profile-card">
        <div class="card-image">
            <%= image_tag "profile-background-pattern.jpg" %>
            <span class="card-title profile-card-name"><%= @profile.name%></span>
            <%= image_tag @profile.profile_pic_url, :class => "profile-picture" %>
            <%= link_to raw("<i class=\"fa fa-edit\"></i>"), edit_profile_path, method: :get, :class => "btn-floating halfway-fab waves-effect waves-light red" %>
        </div>

        <div class="card-content">
            <div class="center-align">
                <%= link_to @profile.git_url, @profile.git_url %>
            </div>

            <div class="card-content-row">
                <div class="i-container">
                    <i class="fab fa-github brand-logo center"></i>
                </div>
                <p><%= @profile.git_username %></p>
            </div>

            <% if not @profile[:localization].nil? %>
                <div class="card-content-row">
                <div class="i-container">
                    <i class="fas fa-map-marker-alt"></i>
                </div>
                    <p><%= @profile.localization %></p>
                </div>
            <% end %>

            <div class="card-content-row">
                <div class="i-container">
                    <i class="fas fa-star"></i>
                </div>
                <p><%= @profile.stars_given %></p>
            </div>

            <div class="card-content-row">
                <p>Contribuições no último ano:</p>
                <p><%= @profile.last_years_contributions %></p>
            </div>

            <div class="card-content-row">
                <p>Número de seguidores:</p>
                <p><%= @profile.followers %></p>
            </div>

            <div class="card-content-row">
                <p>Seguindo:</p>
                <p><%= @profile.following %></p>
            </div>

            <% if not @profile[:organizations].nil? %>
                <div class="card-content-orgs">

                    <% @profile.organizations.split(', ').each do |organization| %>
                        <div class="chip">
                            <%= organization %>
                        </div>
                    <% end %>
                </div>
            <% end %>

        </div>
    </div>

</div>

<div class="profiles-action-container">
    <%= link_to raw("<i class=\"far fa-trash-alt\">APAGAR</i>"), profile_path, method: :delete, :class => "btn waves-effect waves-light red" %>
    <%= link_to "Atualizar informações do github", refresh_path(@profile) , method: :get, :class => "btn" %>
</div>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>